---

- hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        state: latest
        update_cache: yes
      tags:
        - always

- hosts: applications
  become: true
  roles:
    - python

- hosts: databases
  become: true
  roles:
    - database

- hosts: applications
  become: true
  roles:  
    - django

- hosts: applications
  become: true
  roles: 
    - letsencrypt
