- name: Install Pip 
  apt:
    name: python3-pip
    state: present
  tags:
    - python

- name: Install python3-dev
  apt:
    name: python3-dev
    state: present
  tags:
    - python
    
- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: present
  tags:
    - python
    
- name: Install nginx
  apt:
    name: nginx
    state: present
  tags:
    - python
          
- name: Install curl
  apt:
    name: curl
    state: present
  tags:
    - python
       
       
    