---

- name: prepraring Django app and dependencies
  hosts: all
  become: true
  tasks:

    - name: create static directory
      file:
        path: "{{static_dir}}"
        state: directory
        mode: 0755

    - name: "collectstatic"
      command: "{{app_root_directory}}/{{virtualenv_name}}/bin/python3 {{app_root_directory}}/manage.py collectstatic"
    
    - name: create gunicorn socket file
      template:
        src: gunicorn.socket.j2
        dest: "{{system_path}}/gunicorn.socket"
      
    - name: create gunicorn serviced file
      template:
        src: gunicorn.service.j2
        dest: "{{system_path}}/gunicorn.service"

    - name: set ownership of gunicorn.service file
      file:
        path: "{{app_root_directory}}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: start and enable gunicorn service
      service:
        name: gunicorn.socket
        state: started
        enabled: yes

      
    - name: create nginx conf file
      template:
        src: nginx.conf.j2
        dest: "{{nginx_path}}/{{app_name}}.conf"
    
    - name: restart nginx serivce
      service:
        name: nginx
        state: restarted
    
    
    
      


