---

- name: configure secure mysql
  hosts: all
  become: true
  tasks:

    - name: Set root user password for database
      mysql_user: 
        name: root 
        password: "{{root_password}}"
        login_user: root
        login_password: "{{root_password}}"
        login_host: localhost
        state: present
    
    
    - name: Delete anonymous MySQL user
      mysql_user:
        login_user: root
        login_password: "{{root_password}}"
        name: "" 
        host: "{{item}} "
        state: absent
      with_items:
        - localhost
        - "{{ansible_nodename}}"
    
    - name: Delete Hostname based MySQL user
      mysql_user:
        login_user: root
        login_password: "{{root_password}}"
        name: root 
        host: "{{ansible_nodename}}" 
        state: absent
      
    - name: Remove MySQL test database
      mysql_db:
        login_user: root
        login_password: "{{root_password}}" 
        name: test 
        state: absent

