---

- name: installation of mysql and setup
  hosts: all
  become: true
  tasks:

    - name: Install mysql-server and mysql client and dependencies
      apt:
        name: "{{item}}"
        state: present
      loop: 
        - default-mysql-server
        - default-mysql-client
        - python3-mysqldb
    
    - name: start and enable the mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    



    


    

