---

- name: installation and configuration of virtualenv and django
  hosts: all
  become: true
  tasks:
    
    - name: install git if not installed
      apt: 
        name: git
        state: present

    - name: Install virtual env
      pip:
        name: virtualenv
    
    - name: create app directory
      file:
        path: "{{app_root_directory}}"
        state: directory

    - name: git clone repository
      git:
        repo: git@gitlab.com:Griessmeister/mikenskiet.git
        dest: "{{app_root_directory}}"
        clone: yes

    - name: "create virataul env"
      command: 
        chdir: "{{app_root_directory}}"
        cmd: virtualenv "{{virtualenv_name}}"

    - name: apt install default-libmysqlclient-dev
      apt:
        name: default-libmysqlclient-dev
        state: present

    - name: install packages for django env
      pip:
        virtualenv: "{{app_root_directory}}/{{virtualenv_name}}"
        name: ["django","gunicorn","mysqlclient"]
    
    - name:
      pip:
          requirements: "{{app_root_directory}}/requirements.txt"
          virtualenv: "{{app_root_directory}}/{{virtualenv_name}}"
          