---

- name: installation of python, pip and dependencies
  hosts: all
  become: true
  tasks:

    - name: Update packages caches
      apt:
        update_cache: yes
    
    - name: Install Pip 
      apt:
        name: python3-pip
        state: present
    
    - name: Install python3-dev
      apt:
        name: python3-dev
        state: present
        
    - name: Install libpq-dev
      apt:
        name: libpq-dev
        state: present
       
    - name: Install nginx
      apt:
        name: nginx
        state: present
             
    - name: Install curl
      apt:
        name: curl
        state: present
       
       